### ISSUE TITLE
Is this module really work?

### ISSUE THREAD

**Issue by Aetet** [steelbrain/declarations#10]
Is this module work? I need this module for:

go to declaration for es6 imports:
```js
import Hello from './Hello';
``

go to declaration flow type imports:
```js
import type Hello from './HelloType';
```

Even if I use absolute path inside my project f.e. 
```js
import type Hello from 'my-project/common/HelloType';
```

Currently it does not work for any of this case.

**Comment by steelbrain** [comment]
Hi @Aetet!

This module works, but is just the base module. To get it working with javascript files you need to install `declarations-js` :)
