### ISSUE TITLE
Compatibility with Hyperclick Providers?

### ISSUE THREAD

**Issue by keplersj** [steelbrain/declarations#2]
Could this consume the Hyperclick provider so I can have Click-to-Symbol without needing all of Nuclide?

**Comment by steelbrain** [comment]
Yes it can be used instead of hyperclick, though the API is a bit different, we can add a bit compatibility layer to make it work

**Comment by keplersj** [comment]
Woot!

**Comment by steelbrain** [comment]
@kepler0 Can you point me at the hyperclick provider you're using?

**Comment by keplersj** [comment]
@steelbrain I actually haven't been using one lately, sorry.

**Comment by keplersj** [comment]
I have a feeling @hedefalk could use this in Ensime...

**Comment by hedefalk** [comment]
In the field of hyperclicks, I've been through using my own, AsaAyers, my own again, and then hyperclick. 

Currently:
https://github.com/ensime/ensime-atom/blob/v0.37.2/lib/ensime.coffee#L351
- We kind of need the click to be async, can't enumerate all locations.
- Hyperclick does the tokenization of the buffer. We could do it ourselves, probably more reliably, but is good enough now anyways, so seems like some work to use this one as is.

Didn't know hyperclick pulled in entire nuclide?

**Comment by steelbrain** [comment]
@hedefalk `hyperclick` is no longer maintained, it's latest version is part of the `nuclide` package, `nuclide` is too much bloatware of a dependency

**Comment by hedefalk** [comment]
@steelbrain Ah, ok. Yeah, I see there's no release since nov: https://github.com/facebooknuclideapm/hyperclick/releases

Guess I'll need to replace it sooner or later then. Anyways, do you see the two points I gave above reasonable?

**Comment by hedefalk** [comment]
I mean that the source location needs to be on-demand and async:

```
getDeclarations: function({textEditor, visibleRange}) {
        // Note: You can also return a Promise
        return [
          {
            range: [[0, 0], [0, 4]],
            source: function() {
              promise of {
                filePath: '/tmp/test.txt',
                position: [5, 0]
              };
            }
          }
        ]
      }
```

**Comment by steelbrain** [comment]
The declaration API is async already, just return a promise and it'll wait. It gives you a visible range so you can generate AST and then generate declarations for references in that range (saving CPU resources). It does not expose clicking ability to providers and handles it itself.

`declarations` is a language independent package, therefore it does not do any language handling by itself and leaves it for providers to do.

In the declarations API, you must provide a location for the jump beforehand, therefore if you want to detect locations asyncly, you should return a promise that resolves when all the resolution of paths is done.

An example of such package would be

``` js
async getDeclarations({textEditor, visibleRange}) {
  const intentions = await magically_get_declarations()
  for (const intention of intentions) {
    intention.source.filePath = await get_intention_filePath(intention)
  }
  return intentions
}
```

**Comment by hedefalk** [comment]
That still means we have to make one server call per visible token which performance-wise isn't very good. I need it to be on-demand, once you actually click. The server is quick enough that it isn't a problem ux-wise, but making an http-call for every symbol on screen will take CPU-cycles which I'm all for minimizing.

**Comment by steelbrain** [comment]
1. You should only highlight which you are sure of that a definition exists
2. You could batch calls on the server side

If you don't have file paths of declarations before hand, I think it violates 1 unless you confirm it by requesting. You could always batch the calls with this instead

``` js
async getDeclarations({textEditor, visibleRange}) {
  const intentions = await magically_get_declarations()
  await Promise.all(intentions.map(async function(intention) {
    intention.source.filePath = await get_intention_filePath(intention)
  }))
  return intentions
}
```

**Comment by hedefalk** [comment]
Yeah, I really can't to do 1 actually.

This just boils down to waiting for the whole batch of requests before returning my list. Will probably feel laggy before any underlines are shown then…?

I truly want the filePath to be on-demand.

**Comment by steelbrain** [comment]
If you truly want filePath to be on-demand, you could do something like this

``` js
message = {
  range: [...range...],
  source: {
    get filePath(){  return sync_operation_to_get_filePath() }
  }
}
```

**Comment by hedefalk** [comment]
Blocking UI with http request?

**Comment by steelbrain** [comment]
one http request would take 50 ms at the most, a few frames will be missed but because the user isn't typing when he clicks the jump to declarations, he won't even feel it

**Comment by hedefalk** [comment]
50 seconds? ms?

**Comment by steelbrain** [comment]
s/seconds/ms/

**Comment by keplersj** [comment]
Guys... This issue is about using `declarations` as a `hyperclick` drop-in replacement.

**Comment by steelbrain** [comment]
Thanks for reminding @kepler0 :stuck_out_tongue: 
@hedefalk If you want to discuss this further, I'll be available in Atom Slack

**Comment by keplersj** [comment]
:grinning:

**Comment by hedefalk** [comment]
@kepler0 Yeah, but I actually think we're pretty much on topic? :)

@steelbrain Thanks for your patience as always. I need to go to bed and this isn't really at the top of my list right now anyways. Never been to Atom slack, but I will check it out if I have the time!

But I think we truly are discussing the original topic here. I mean, I'm currently using `hyperclick` but can't replace it with `declarations` with my current requirements which are:
- Don't ask for location (http request per symbol) until click
- Don't block.

I believe it would be pretty easy to implement on-demand support for the location of a symbol though?

My prio list:
- Continue using hyperclick as it works for us without those issues.
- If hyperclick becomes a burden, check back here if you've fixed on-demand support for location.
- If not, nag
- If nag no work, fork. :)

**Comment by steelbrain** [comment]
@hedefalk the support for async sources have landed in the latest version btw, check the docs for new API

**Comment by hedefalk** [comment]
@steelbrain Awesome! Thanks a lot, I'm gonna check it out as soon as I get a bit of time.
